name: Java CI with Maven

on:
#  запуск при push
  push:
    branches: [ main ]
#  запуск при pull
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  # запуск workflow вручную из веб-интерфейса GitHub
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
#        проверка
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        # используем JDK21

        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Build with Maven  # так как собирали с Maven, указываем это
        run: mvn -B package --file pom.xml
        # пакетный режим + указываем pom-ник

      - name: Run tests
        run: mvn test
        # запуск тестов
      - name: Notify Telegram Success
        if: success()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.7034034388:AAEaAOiARBc0rCdJgGfrzkhUziYQlIeBkJU }}/sendMessage -d chat_id=${{ secrets.840472850 }} -d text="✅🐈Сборка и тесты прошли успешно"

      - name: Notify Telegram NOT Success
        if: failure()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.7034034388:AAEaAOiARBc0rCdJgGfrzkhUziYQlIeBkJU }}/sendMessage -d chat_id=${{ secrets.840472850 }} -d text="⚡️Сборка или тесты не прошли"
